#服务端口
server:
  port: 8003

# 服务名
spring:
  application:
    name: service8003-vod

  #    环境设置:dev test prod
  profiles:
    active: dev

  # 最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
  # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848




