server:
    port: 8008
spring:
    application:
        name: service8008-statistics
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    #mysql数据库连接
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/online_edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:edu/zsq/statistics/mapper/xml/*.xml