server:
    port: 10002
spring:
    application:
        name: service10002-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                #id随意 一般和服务名一致
            -   id: service8001-edu
                #匹配路径
                predicates: Path=/eduService/**
                #lb://nacos注册服务名 lb负载均衡
                uri: lb://service8001-edu

            -   id: service8004-cms
                predicates: Path=/eduCms/**
                uri: lb://service8004-cms


            -   id: service8007-order
                predicates: Path=/orderService/**
                uri: lb://service8007-order

            -   id: service8009-acl
                predicates: Path=/*/acl/**
                uri: lb://service8009-acl

            -   id: service8150-user
                predicates: Path=/user/**
                uri: lb://service8150-user

        nacos:
            discovery:
                server-addr: 192.168.88.128:8848

