#服务端口
server:
  port: 8150

#服务名
spring:
  application:
    name: service8150-user

    #环境设置
  profiles:
    active: dev

  # 时间格式和时区设置
  jackson:
    date-format: yyyy-MM-dd  HH:mm:ss
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.33.129
    port: 6379
    password: root
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        #最大活动对象数
        maxTotal: 1000
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0



  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://online-edu.mysql.rds.aliyuncs.com:3306/online_edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: zhangsongqi
    password: Zsq060606



mybatis-plus:
  mapper-locations: classpath:edu/zsq/user/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#ribbon的超时时间
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000


#开启熔断机制
feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100

logging.level.com.alibaba.nacos.client.naming: WARN

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
  # 微信开放平台 appsecret
  app_secret: a7482517235173ddb4083788de60b90e
  # 微信开放平台 重定向url
  redirect_url: http://guli.shop/api/ucenter/wx/callback