#server:
#    port: 8009
#spring:
#    application:
#        name: service8009-acl
#
#    #环境设置
#    profiles:
#        active: dev
#
#    #mysql数据库连接
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3307/fake_foreigner?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: root
#    jackson:
#        date-format: yyyy-MM-dd HH:mm:ss
#        time-zone: GMT+8
#
#    # nacos服务地址
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 127.0.0.1:8848
#    redis:
#        host: 192.168.33.129
#        port: 6379
#        password: root
#        database: 0
#        timeout: 1800000
#
#        lettuce:
#            pool:
#                #最大活动对象数
#                maxTotal: 1000
#                max-active: 20
#                max-wait: -1
#                #最大阻塞等待时间(负数表示没限制)
#                max-idle: 5
#                min-idle: 0
#
#mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapper-locations: classpath:edu/zsq/acl/mapper/xml/*.xml