server:
    port: 8007
spring:
    application:
        name: service8007-order
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    #mysql数据库连接
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/online_edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8


mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:com/atguigu/orderservice/mapper/xml/*.xml

logging.level.com.alibaba.nacos.client.naming: WARN

tx:
    wx:
        appId: wx74862e0dfcf69954
        partner: 1558950191
        partnerKey : T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
        notifyUrl: http:// guli.shop/api/order/weixinPay/weixinNotify
