server:
    port: 8010
spring:
    application:
        name: canal8010-client
    #mysql数据库连接
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/online_edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
    profiles:
        active: dev
